spring:
  datasource:
    url: jdbc:postgresql:product
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    rest:
      base-path: /api

server:
  port: 8888
