spring:
  datasource:
    url: jdbc:postgresql:jpa
    username: postgres
    password: Hoaibao211
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect