spring:
  datasource:
    url: jdbc:postgresql:product
    username: postgres
    password: Hoaibao211
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    rest:
      base-path: /api
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379