spring:
  datasource:
    url: jdbc:postgresql:product
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8888